
services:
  hop-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hopweb-dataspeed
    container_name: hopcontainer-data-eng
    user: "0:0" 
    environment:
      - HOP_PROJECT_FOLDER=/usr/local/tomcat/webapps/ROOT/project
      - HOP_PROJECT_NAME=hopdbt
      - HOP_ENVIRONMENT_NAME=hopdbt-dev
      - HOP_ENVIRONMENT_CONFIG_FILE_NAME_PATHS=/usr/local/tomcat/webapps/ROOT/config/hopdbt-dev.json
      - HOP_ENVIRONMENT-PURPOSE=Development
      - HOP_CONFIG_FOLDER=/usr/local/tomcat/webapps/ROOT/config
      - HOP_WEB_THEME=light

     # AWS credentials
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
 

    ports:
      - "8085:8080"
    volumes:
      - ./projeto_hop:/usr/local/tomcat/webapps/ROOT/project
      - ./config_hop:/usr/local/tomcat/webapps/ROOT/config
    networks:
      - hopdbt-network

  jenkins:
    build:
      context: ./jenkins_home
      dockerfile: Dockerfile
    image: jenkins-dataspeed
    container_name: jenkins-data-eng
    ports:
      - "8095:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - hopdbt-network

  dbt:
    build:
      context: ./projeto_dbt
      dockerfile: Dockerfile
    image: imgdbt-dbt-dataspeed
    container_name: dbt-dbt-data-eng
    ports:
      - "9100:8080"
    volumes:
      - ./projeto_dbt/dbt:/dbt
      - ./projeto_dbt/profiles:/root/.dbt/
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - hopdbt-network

  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5444:5432'
    volumes:
      - ./db_data_dw:/var/lib/postgresql/data
    container_name: postgres-dw-data-eng
    networks:
      - hopdbt-network

volumes:
  db_data:
    driver: local

networks:
  hopdbt-network:
    external: true
